name: Run tests

on: [ push, pull_request ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql57:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: forge
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        php: [ 8.1, 8.2 ]
        stability: [ prefer-stable ]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Setup Swagger
        run: php artisan l5-swagger:generate

      - name: phpcs
        run: ./vendor/bin/phpcs

      - name: phpstan
        run: ./vendor/bin/phpstan analyse

      - name: Execute tests
        run: ./vendor/bin/phpunit
